# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - 'docker.env'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
