export const GET_PRODUCT = 'Get product successfully'
export const GET_PRODUCTS = 'Get all products successfully'
export const PRODUCT_UPDATED = 'product Updated'
export const PRODUCT_DELETED = 'product Deleted'
export const PRODUCT_CREATED = 'product created'